services:
  tailscale:
    image: tailscale/tailscale:stable
    hostname: ${TAILSCALE_HOSTNAME}
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_HOSTNAME=${TAILSCALE_HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-routes
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale:/var/lib/tailscale
    restart: unless-stopped

  sync-service:
    image: ubuntu:20.04
    container_name: sync-service
    depends_on:
      - tailscale
    privileged: true
    env_file:
      - .env
    network_mode: "service:tailscale"
    volumes:
      - ./sync-data:/mnt/sync
      - ./tasks:/opt/tasks:ro
      - ./env.sh:/opt/env.sh:ro
    entrypoint: ["/opt/tasks/entrypoint.sh"]
